apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: garage
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: garage-secrets
    creationPolicy: Owner
  data:
    - secretKey: RPC_SECRET
      remoteRef:
        key: homelab/k8s-garage/rpc-secret
        property: value
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: homelab/k8s-garage/admin-token
        property: value
    - secretKey: METRICS_TOKEN
      remoteRef:
        key: homelab/k8s-garage/metrics-token
        property: value
