apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: garage
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: garage-secrets
    creationPolicy: Owner
  data:
    - secretKey: RPC_SECRET
      remoteRef:
        key: homelab/garage
        property: RPC_SECRET
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: homelab/garage
        property: ADMIN_TOKEN
    - secretKey: METRICS_TOKEN
      remoteRef:
        key: homelab/garage
        property: METRICS_TOKEN
